// ------------------------------------------------------------
// Copyright (c) Microsoft Corporation.  All rights reserved.
// ------------------------------------------------------------

namespace Azure.Data.Cosmos.Shell.Core;

/// <summary>
/// Specifies the format of the output generated by the shell.
/// </summary>
public enum OutputFormat
{
    /// <summary>
    /// Output in JSON format.
    /// </summary>
    JSon,

    /// <summary>
    /// Output in CSV format.
    /// </summary>
    CSV,

    /// <summary>
    /// Output as an aligned text table.
    /// </summary>
    Table,

    /// <summary>
    /// Output in Newline Delimited JSON (NDJSON) format.
    /// </summary>
    NDJson,

    /// <summary>
    /// Output in JSON format wrapped in a structured execution envelope.
    /// </summary>
    JsonFull,
}
