// ------------------------------------------------------------
// Copyright (c) Microsoft Corporation.  All rights reserved.
// ------------------------------------------------------------

namespace Azure.Data.Cosmos.Shell.Core;

/// <summary>
/// Specifies the format of the output generated by the shell.
/// </summary>
public enum OutputFormat
{
    /// <summary>
    /// Render the result for a human via the command's <see cref="CommandState.RenderUser"/>
    /// delegate when writing to an interactive terminal; falls back to JSON otherwise.
    /// </summary>
    User,

    /// <summary>
    /// Output in JSON format.
    /// </summary>
    JSon,

    /// <summary>
    /// Output in CSV format.
    /// </summary>
    CSV,

    /// <summary>
    /// Output as an aligned text table.
    /// </summary>
    Table,
}
